Dataset:
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.05

Training:
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  size_threshold: 20
  rgb_boundary_threshold: 0.01
  lambda_dnormal: 0.1
  compensate_exposure: false

opt_params:
  pose_lr: 0.0001
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densify_grad_threshold: 0.0002
